module CORBAHello
{
	const long SOME_NUMBER = 1000;

	struct PersonData
	{
		unsigned long id;
		string name;
	};

	typedef sequence<PersonData>		PersonDataSeq;

	interface Echo
	{
		string sendMsg(in string message);
		void fillPersonDataSeq(	in unsigned long size,
								out PersonDataSeq dataSeq);
	};

}; //CORBAHello ends

